#This dockerfile is created for building image from energi core node
#https://s3-us-west-2.amazonaws.com/download.energi.software/releases/energi3/v3.1.3/energi3-v3.1.3-linux-amd64.tgz


FROM openjdk:8-alpine
RUN apk update && apk add /bin/sh
RUN mkdir -p /opt/app
ADD https://s3-us-west-2.amazonaws.com/download.energi.software/releases/energi3/v3.1.3/energi3-v3.1.3-linux-amd64.tgz /opt/app/
RUN cd /opt/app/ \ && tar -xvzf energi3-v3.1.3-linux-amd64.tgz
COPY . .
CMD ["java" ,"-jar"]


#Please check Readme for output of docker the file.


