#This dockerfile is created for building image from energi core node
#https://s3-us-west-2.amazonaws.com/download.energi.software/releases/energi3/v3.1.3/energi3-v3.1.3-linux-amd64.tgz


FROM openjdk:8-alpine
RUN apk update && apk add /bin/sh
RUN mkdir -p /opt/app
ADD https://s3-us-west-2.amazonaws.com/download.energi.software/releases/energi3/v3.1.3/energi3-v3.1.3-linux-amd64.tgz /opt/app/
RUN cd /opt/app/ \ && tar -xvzf energi3-v3.1.3-linux-amd64.tgz
COPY . .
CMD ["java" ,"-jar"]


<img width="997" alt="Screen Shot 2022-10-08 at 05 44 10" src="https://user-images.githubusercontent.com/115284052/194711451-7fc76bdb-e852-4d27-b085-17b82c7c9254.png">



