#This is a Kubernetes statefulset with volume claim and resource request from EKS cluster.



apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: energi
spec:
  serviceName: "energisvc"
  selector:
    matchLabels:
      app: energi3
  replicas: 2
  template:
    metadata:
      labels:
        app: energi3
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: energi
        image: energi/energi:v3.1.3
        resources:
          limits:
            memory: 1Gi
        ports:
        - containerPort: 00
        volumeMounts:
        - name: energi-data
          mountPath: /usr/share/energi
  volumeClaimTemplates:
  - metadata:
      name: energi-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassname: standard
      resources:
        requests:
          storage: 1Gi
